
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrftbhmnqrdogomhvomr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyZnRiaG1ucXJkb2dvbWh2b21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MzYzNDcsImV4cCI6MjA1OTUxMjM0N30.S7MaDuJnQcXXTZBKbYYeo2jrknbB3eejGn3Z6Fkxarc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
